kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fips-image-build-flannel
  image: docker:latest
  volumes:
  - name: deps
    path: /go
  when:
    instance:
    - drone-publish.rancher.io
    event:
    - tag
    - push
  commands:
  - make
  - make image-push
  - make image-manifest
