---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fips-image-build-flannel
  image: docker:latest
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - apk update && apk add make
  - make
  when:
    event:
    - tag
    - push

- name: fips-image-push-flannel
  image: docker:latest
  commands:
  - apt update && apt install -y build-essential
  - make image-push

  when:
    event:
    - tag
    - push

- name: fips-image-manifest-flannel
  image: docker:latest
  commands:
  - apt update && apt install -y build-essential
  - make image-manifest
  when:
    event:
    - tag
    - push

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
