---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fips-image-build-flannel
  image: docker:latest
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - docker -v
  - make image-push
  - make image-manifest
  when:
    event:
    - tag
    - push
