---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fips-image-build-flannel
  image: ubuntu:latest
  volumes:
  - name: deps
    path: /go
  commands:
  - apt install build-essential
  - make
  - make image-push
  - make image-manifest
  when:
    event:
    - tag
    - push
