---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: briandowns/rancher-build-base:v0.1.0
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - sleep 20
  #- apk update && apk add make
  - make
  when:
    event:
    - tag
    - push

- name: push
  image: briandowns/rancher-build-base:v0.1.0
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  #- apk update && apk add make
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make image-push
  environment:
    DOCKER_USERNAME: 
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - tag

- name: scan
  image: briandowns/rancher-build-base:v0.1.0
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  #- apk update && apk add make wget jq rpm
  #- wget https://github.com/aquasecurity/trivy/releases/download/v0.6.0/trivy_0.6.0_Linux-64bit.tar.gz
  #- tar -zxf trivy_0.6.0_Linux-64bit.tar.gz
  #- mv trivy /usr/local/bin
  - make image-scan
  when:
    event:
    - tag

- name: manifest
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  #- apk update && apk add make jq
  - make image-manifest
  when:
    event:
    - tag

services:
- name: docker
  image: briandowns/rancher-build-base:v0.1.0
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
