---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fips-image-build-flannel
  image: docker:latest
  volumes:
  - name: deps
    path: /go
  commands:
  - apt update
  - apt install -y build-essential docker.io systemd
  - systemctl start docker
  - make
  - make image-push
  - make image-manifest
  when:
    event:
    - tag
    - push
