---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fips-image-build-flannel
  image: briandowns/rancher-base-build:v0.1.0
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - docker build -t briandowns/fips-image-build-flannel:v0.12.0 .
  - make
  - make image-push
  - make image-manifest
  when:
    event:
    - tag
    - push
