kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fips-image-build-flannel
  image: goboring/golang:1.10.3b4
  volumes:
  - name: deps
    path: /go
  when:
    instance:
      - drone-publish.rancher.io
    event:
      - tag
      - push
  commands:
  - make
  - make image-push
  - make image-manifest
