---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fips-image-build-flannel
  image: docker:latest
  volumes:
  - name: deps
    path: /go
  - name: docker socket
    path: /root/.docker:/root/.docker
  commands:
  - docker build -t briandowns/fips-image-build-flannel:v0.12.0 .
  - make
  - make image-push
  - make image-manifest
  when:
    event:
    - tag
    - push
